In [36]:
import pandas as pd

In [37]:
data = {
    "Hours_studied" :[1,2,3,4,5,6,7,8,9,10],
    "Passed":[0,0,0,0,0,1,1,1,1,1]
}

In [38]:
df = pd.DataFrame(data)

In [39]:
df

   Hours_studied  Passed
0              1       0
1              2       0
2              3       0
3              4       0
4              5       0
5              6       1
6              7       1
7              8       1
8              9       1
9             10       1

In [54]:
X = df[["Hours_studied"]]
y = df["Passed"]

In [55]:
print(X)

   Hours_studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10

In [56]:
print(y)

0    0
1    0
2    0
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: Passed, dtype: int64

In [57]:
import sklearn

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [60]:
print(X_train)

   Hours_studied
5              6
0              1
7              8
2              3
9             10
4              5
3              4
6              7

In [61]:
print(X_test)

   Hours_studied
8              9
1              2

In [62]:
print(y_train)

5    1
0    0
7    1
2    0
9    1
4    0
3    0
6    1
Name: Passed, dtype: int64

In [63]:
print(y_test)

8    1
1    0
Name: Passed, dtype: int64

In [64]:
# logistic regression

In [65]:
from sklearn.linear_model import LogisticRegression

In [66]:
model = LogisticRegression()

In [67]:
model.fit(X_train , y_train)

LogisticRegression()

In [68]:
y_pred = model.predict(X_test)

In [69]:
y_pred

array([1, 0])

In [71]:
y_test

8    1
1    0
Name: Passed, dtype: int64

In [72]:
X_test

   Hours_studied
8              9
1              2

In [83]:
new_hours = pd.DataFrame({"Hours_studied":[7.5,11,2.5]})

In [84]:
new_hours

   Hours_studied
0            7.5
1           11.0
2            2.5

In [85]:
predicted_result = model.predict(new_hours)

In [86]:
predicted_result

array([1, 1, 0])

In [88]:
from sklearn.metrics import mean_squared_error

In [89]:
mean_squared_error(y_test,y_pred)

0.0

In [93]:
model.score(X_test,y_test)

1.0

In [94]:
y_prob = model.predict_proba(X_test)

In [95]:
y_prob

array([[0.01799637, 0.98200363],
       [0.98200563, 0.01799437]])