In [1]:
import numpy as np

In [2]:
a = np.array([12,33.5,True,'aryan'])

In [3]:
a

array(['12', '33.5', 'True', 'aryan'], dtype='<U32')

In [4]:
# pandas dataframe

In [13]:
# Dataframe : manually

In [5]:
import pandas as pd

In [9]:
roll = pd.Series([1,2,3,4,5])
name = pd.Series(['sia','ravi','geet','ajeenkya','avinash'])
marks = pd.Series([85,67,59,40,90])

In [11]:
df = pd.DataFrame({
    'id':roll,
    'name':name,
    'marks':marks
})

In [12]:
df

   id      name  marks
0   1       sia     85
1   2      ravi     67
2   3      geet     59
3   4  ajeenkya     40
4   5   avinash     90

In [14]:
df.ndim

2

In [15]:
df.shape

(5, 3)

In [16]:
df.size

15

In [17]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [19]:
pwd

'C:\\Users\\Tajeswini\\internship 26'

In [28]:
# Dataframe : via datasets

In [20]:
df = pd.read_csv("student.csv")

In [21]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [22]:
df.shape

(10, 5)

In [23]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [32]:
col = ['roll','name','class','marks']

In [33]:
df1 = pd.read_csv("student1.csv" , names = col)

In [34]:
df1

       roll name  class  marks
1      anil   TE  56.77     22
2      amit   TE  59.77     21
3    aniket   BE  76.88     19
4   ajinkya   TE  69.66     20
5      asha   TE  63.28     20
6    ayesha   BE  49.55     20
7      amar   BE  65.34     19
8     amita   BE  68.33     23
9      amol   TE  56.75     20
10    anmol   BE  78.66     21

In [40]:
df3 = pd.read_csv("student3.tsv" , sep = '\t')

In [41]:
df3

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21